image: mono:4.4.0.182

stages:
  - build

before_script:
  - 'nuget restore MvcApplication1.sln'

build:
 stage: build
 script:
  - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Release" /p:Platform="Any CPU" MvcApplication1.sln
 only:
   - master